/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART_1.h"
#include "UART_1_SPI_UART.h"
#include "UART_1_PINS.h"
#include "UART_1_SPI_UART_PVT.h"
#include "UART_1_PVT.h"
#include "UART_1_BOOT.h"
#include "DEBUGPIN0.h"
#include "DEBUGPIN0_aliases.h"
#include "LED_R.h"
#include "LED_R_aliases.h"
#include "DEBUGPIN1.h"
#include "DEBUGPIN1_aliases.h"
#include "isr_1.h"
#include "P2_4_A_PH.h"
#include "P2_4_A_PH_aliases.h"
#include "P2_6_B_PH.h"
#include "P2_6_B_PH_aliases.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "Clock_1.h"
#include "P2_5_A_EN.h"
#include "P2_5_A_EN_aliases.h"
#include "P2_7_B_EN.h"
#include "P2_7_B_EN_aliases.h"
#include "P2_3_MODE.h"
#include "P2_3_MODE_aliases.h"
#include "UART_1_SCBCLK.h"
#include "UART_1_tx.h"
#include "UART_1_tx_aliases.h"
#include "UART_1_rx.h"
#include "UART_1_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

