/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USER_PORT.h"
#include "USER_PORT_I2C.h"
#include "USER_PORT_SPI_UART.h"
#include "USER_PORT_PINS.h"
#include "USER_PORT_I2C_PVT.h"
#include "USER_PORT_SPI_UART_PVT.h"
#include "USER_PORT_PVT.h"
#include "USER_PORT_EZI2C.h"
#include "USER_PORT_EZI2C_PVT.h"
#include "USER_PORT_BOOT.h"
#include "DEBUGPIN0.h"
#include "DEBUGPIN0_aliases.h"
#include "LED_R.h"
#include "LED_R_aliases.h"
#include "DEBUGPIN1.h"
#include "DEBUGPIN1_aliases.h"
#include "SCBCLK.h"
#include "P2_4_A_PH.h"
#include "P2_4_A_PH_aliases.h"
#include "P2_6_B_PH.h"
#include "P2_6_B_PH_aliases.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "Clock_1.h"
#include "P2_5_A_EN.h"
#include "P2_5_A_EN_aliases.h"
#include "P2_7_B_EN.h"
#include "P2_7_B_EN_aliases.h"
#include "P2_3_MODE.h"
#include "P2_3_MODE_aliases.h"
#include "DEBUGPIN2.h"
#include "DEBUGPIN2_aliases.h"
#include "DEBUGPIN3.h"
#include "DEBUGPIN3_aliases.h"
#include "USER_PORT_spi_sclk.h"
#include "USER_PORT_spi_sclk_aliases.h"
#include "USER_PORT_spi_mosi_i2c_scl_uart_rx.h"
#include "USER_PORT_spi_mosi_i2c_scl_uart_rx_aliases.h"
#include "USER_PORT_spi_miso_i2c_sda_uart_tx.h"
#include "USER_PORT_spi_miso_i2c_sda_uart_tx_aliases.h"
#include "USER_PORT_spi_ss0.h"
#include "USER_PORT_spi_ss0_aliases.h"
#include "USER_PORT_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

