# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\github\Serial_Controlled_Motor_Driver\Firmware\PSoC Projects\Dev_Kit_Debug\Design02.cydsn\Design02.cyprj
# Date: Mon, 23 May 2016 20:34:27 GMT
#set_units -time ns
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]


# Component constraints for C:\github\Serial_Controlled_Motor_Driver\Firmware\PSoC Projects\Dev_Kit_Debug\Design02.cydsn\TopDesign\TopDesign.cysch
# Project: C:\github\Serial_Controlled_Motor_Driver\Firmware\PSoC Projects\Dev_Kit_Debug\Design02.cydsn\Design02.cyprj
# Date: Mon, 23 May 2016 20:34:24 GMT
